version: "3.8"
services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - USER=trans #optional
      - PASS=mission #optional
    volumes:
      - /storage/transmission:/config
      - /var/media/data:/media/data
      - /var/media/data/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    network_mode: bridge

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /storage/jackett:/config
      - /var/media/data:/media/data
    ports:
      - 9117:9117
    restart: unless-stopped
    network_mode: bridge

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /storage/sonarr:/config
      - /var/media/data:/media/data
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: bridge

  radarr:
    image: linuxserver/radarr:arm32v7-nightly
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /storage/radarr:/config
      - /var/media/data:/media/data
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: bridge

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /storage/bazarr:/config
      - /var/media/data:/media/data
    ports:
      - 6767:6767
    restart: unless-stopped
    network_mode: bridge

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /storage/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    network_mode: bridge

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:arm
    ports:
      - "5054:5054/udp"
    restart: unless-stopped
    network_mode: bridge

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
    environment:
      TZ: 'Asia/Jakarta'
    volumes:
      - '/storage/pihole/config/:/etc/pihole/'
      - '/storage/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    network_mode: bridge

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - /storage/jellyfin:/config
      - /var/media/data/Series:/data/tvshows
      - /var/media/data/Movies/:/data/movies
      # - /opt/vc/lib:/opt/vc/lib
    ports:
      - 8096:8096
    # devices:
    #   - /dev/vcsm:/dev/vcsm
    #   - /dev/vchiq:/dev/vchiq
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: bridge
