version: "3.8"
services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - TZ=Asia/Jakarta
      - USER=trans #optional
      - PASS=mission #optional
    volumes:
      - /storage/transmission:/config
      - /var/media/data:/media/data
      - /var/media/data/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    network_mode: bridge

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /storage/sabnzbd:/config
      - /var/media/data:/media/data
    ports:
      - 8765:8080
    restart: unless-stopped
    network_mode: bridge

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /storage/jackett:/config
      - /var/media/data:/media/data
    ports:
      - 9117:9117
    restart: unless-stopped
    network_mode: bridge

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /storage/sonarr:/config
      - /var/media/data:/media/data
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: bridge

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /storage/radarr:/config
      - /var/media/data:/media/data
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: bridge

  bazarr:
    image: linuxserver/bazarr:development
    container_name: bazarr
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /storage/bazarr:/config
      - /var/media/data:/media/data
    ports:
      - 6767:6767
    restart: unless-stopped
    network_mode: bridge

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /storage/prometheus/data:/prometheus
      - /storage/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9191:9090
    restart: unless-stopped
    network_mode: bridge

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /storage/grafana/data:/var/lib/grafana
      - /storage/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 9300:3000
    restart: unless-stopped
    network_mode: bridge

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /storage/.docker/config.json:/config.json
    restart: unless-stopped
    network_mode: bridge

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - /storage/plex:/config
      - /var/media/data:/media/data
    restart: unless-stopped
